//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitas
    {
        public int idVisitas { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan HoraEntrada { get; set; }
        public System.TimeSpan HoraSalida { get; set; }
        public string Motivo_Visita { get; set; }
        public Nullable<int> Persona { get; set; }
        public Nullable<int> Area { get; set; }
    
        public virtual Area Area1 { get; set; }
        public virtual Persona Persona1 { get; set; }
    }
}
